name: Kenrick Turner
description: Writings and talks by Kenrick Turner. Kenrick is a doctor with the British Antarctic Survey.
blurb: Our Man in Antarctica
pygments: true
url: http://kenners.org
permalink: /:categories/:title
relative_permalinks: false
timezone: Europe/London

pygments: true
markdown: kramdown
rdiscount:
  extensions: [footnotes]

include: ['.htaccess']
exclude: ['config.rb','Rakefile','s3_website.yml','_templates']
excerpt_separator: "\n\n"

flickr:
  cache_dir:       ./_cache/flickr
  api_key:          203adaf5991963a3f7eb4ec52f2804ec
  shared_secret:    b428b2e80fb1d978
  access_token:     72157634699050129-a50586626b9cb4f6
  access_secret:    3a6e608c9c47b56f

countdown:
  dday: 2013-11-03